import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { detectAllLinters, type DetectionResult } from './utils/detect.js';
import { CONFIG_FILES, CONFIG_DEFAULTS } from './config.js';

/**
 * Generate JSONC config content from detection results
 */
function generateConfig(results: DetectionResult[]): string {
  const lines: string[] = [
    '{',
    '  // Generated by lintmesh init',
    '  // Docs: https://github.com/...',
    '  "$schema": "https://unpkg.com/lintmesh/schema.json",',
    '',
    '  "linters": {',
  ];

  const enabledLinters = results.filter(r => r.recommended);
  const availableLinters = results.filter(r => r.available && !r.recommended);
  const unavailableLinters = results.filter(r => !r.available);

  // Add enabled linters
  enabledLinters.forEach((r, i) => {
    const isLast = i === enabledLinters.length - 1 && availableLinters.length === 0;
    const comma = isLast ? '' : ',';
    const source = r.binSource === 'local' ? 'node_modules' : 'PATH';
    const version = r.version ? ` v${r.version}` : '';
    const config = r.configPath ? `, config: ${path.basename(r.configPath)}` : '';

    lines.push(`    "${r.linterId}": {`);
    lines.push(`      "enabled": true  // resolved: ${source}${version}${config}`);
    lines.push(`    }${comma}`);
  });

  // Add available but not recommended (commented)
  availableLinters.forEach((r, i) => {
    const isLast = i === availableLinters.length - 1;
    const comma = isLast ? '' : ',';
    const source = r.binSource === 'local' ? 'node_modules' : 'PATH';
    const version = r.version ? ` v${r.version}` : '';

    lines.push(`    // "${r.linterId}": { "enabled": false }  // available (${source}${version}) but no config`);
  });

  lines.push('  },');
  lines.push('');

  // Add defaults as comments for reference
  lines.push(`  "include": ${JSON.stringify(CONFIG_DEFAULTS.include)},`);
  lines.push(`  "exclude": ${JSON.stringify(CONFIG_DEFAULTS.exclude)},`);
  lines.push(`  "timeout": ${CONFIG_DEFAULTS.timeout},`);
  lines.push(`  "failOn": "${CONFIG_DEFAULTS.failOn}"`);
  lines.push('}');

  return lines.join('\n');
}

export interface InitOptions {
  cwd: string;
  /** Config file path to use (defaults to first CONFIG_FILES entry) */
  output?: string;
  /** Force overwrite if exists */
  force?: boolean;
}

export interface InitResult {
  configPath: string;
  created: boolean;
  detected: DetectionResult[];
}

/**
 * Initialize lintmesh config in project
 */
export async function init(options: InitOptions): Promise<InitResult> {
  const { cwd, force = false } = options;

  // Determine output path
  const configPath = options.output || path.join(cwd, CONFIG_FILES[0]);

  // Check if already exists
  if (existsSync(configPath) && !force) {
    throw new Error(`Config already exists: ${configPath}\nUse --force to overwrite.`);
  }

  // Detect linters
  const detected = await detectAllLinters(cwd);

  // Generate config
  const content = generateConfig(detected);

  // Ensure directory exists
  const dir = path.dirname(configPath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  // Write config
  writeFileSync(configPath, content, 'utf-8');

  return {
    configPath,
    created: true,
    detected,
  };
}

/**
 * Print init result summary to stderr
 */
export function printInitSummary(result: InitResult): void {
  console.error(`Created ${result.configPath}\n`);

  const enabled = result.detected.filter(r => r.recommended);
  const available = result.detected.filter(r => r.available && !r.recommended);

  if (enabled.length > 0) {
    console.error('Enabled linters:');
    for (const r of enabled) {
      const v = r.version ? ` v${r.version}` : '';
      console.error(`  - ${r.linterId}${v}`);
    }
    console.error('');
  }

  if (available.length > 0) {
    console.error('Available but not enabled (no config found):');
    for (const r of available) {
      console.error(`  - ${r.linterId}`);
    }
    console.error('');
  }

  console.error('Run `lintmesh` to lint your project.');
}
